### ISSUE TITLE
Startup fails when using MongoDB 3.6

### ISSUE THREAD

**Issue by thetric** [flapdoodle-oss/de.flapdoodle.embed.mongo#223]
The embedded db fails to start with Mongo 3.6. It errors with

```
o.s.b.a.mongo.embedded.EmbeddedMongo     : Error parsing command line: unrecognised option '--nohttpinterface'
```

The previous version 3.4.10 didn't fail on startup.

I use the embedded db with Spring Boot 1.5.9

**Comment by michaelmosmann** [comment]
Hmm..OK.so we have to add a feature flag to this option.



Am 12. Dezember 2017 16:43:33 schrieb Dominik Broj <notifications@github.com>:

**Comment by poikilotherm** [comment]
Sorry to necro this old issue, please slap me if I should open a new issue instead.

While using 
* Spring Boot 2.0.0
* Spring Data MongoDB 2.0.5
* Flapdoodle 2.0.3

and setting MongoDB version to 3.6.0 or 3.6.3  in application.yaml via
```
spring:
  data:
    mongodb:
      repositories:
        enabled: true
  mongodb:
    embedded:
      version: 3.6.3
```

I receive the exact same error, breaking my unit tests.
The above configuration was taken from #190.

Any hints?
