### ISSUE TITLE
High CPU usage for MongoDB 4.0.2 on Mac OS X

### ISSUE THREAD

**Issue by symphony-youri** [flapdoodle-oss/de.flapdoodle.embed.mongo#322]
Running Embedded MongoDB with Spring Boot on a Mac with version 4.0.2 showed a high CPU usage (~100%) for the mongod process. It seems that disabling syncdelay option (that is set to 0) fixes the issue.

Here is the working configuration from Spring point of view:
```
spring:
  mongodb:
    embedded:
      version: 4.0.2
      # Remove syncdelay options that seems to cause high CPU usage on macosx
      features: STORAGE_ENGINE,ONLY_64BIT,NO_CHUNKSIZE_ARG,MONGOS_CONFIGDB_SET_STYLE,NO_HTTP_INTERFACE_ARG,ONLY_WITH_SSL,ONLY_WINDOWS_2008_SERVER,NO_SOLARIS_SUPPORT
```

I did not dig into more details so not sure if there is an issue here but I though it might help someone else to leave a trace here.
