### ISSUE TITLE
using Libcrypto 3.x isntead of 1.x

### ISSUE THREAD

**Issue by ario-afrashteh** [flapdoodle-oss/de.flapdoodle.embed.mongo#467]
I have updated flapdoodle to 4.7.0 and it requieres libcrypto.so.1.1 which is old and (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Please check [openssl.org](https://www.openssl.org/source/).

**Comment by michaelmosmann** [comment]
@ario-afrashteh which mongodb version and platform are you using?

**Comment by ario-afrashteh** [comment]
@michaelmosmann I'm using Ubuntu 18.04 LTS and I have used below dependencies:
  ```xml
<dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo</artifactId>
      <version>4.7.0</version>
      <scope>test</scope>
  </dependency>
  <dependency>
      <groupId>de.flapdoodle.embed</groupId>
      <artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
      <version>4.7.0</version>
  </dependency>
```

And also this config in my test properties file (I also tried 6.0.6 and it has the same problem):
```yml
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.18
```

**Comment by michaelmosmann** [comment]
@ario-afrashteh as there are binaries for ubuntu 18.04 (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/b86a0fac90241375ba27c53481766e8eba805439/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt#L61) i guess that these versions are using libcrypto1.x .. you can try a version for a newer ubuntu release if you override the os detection (see https://github.com/flapdoodle-oss/de.flapdoodle.os#run) to see if this works.. but i am not sure against which version these binaries are linked.

**Comment by ario-afrashteh** [comment]
I did add these configs as you said:
```yml
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.6
    os:
      explain: true
      override: Linux|X86_64|X86_64|Ubuntu|Ubuntu_18_04

```

I got this error:
2023-07-06T08:08:07.592Z ERROR 865 --- ***       Thread-5*** d.f.e.m.s.a.EmbeddedMongo                :mongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
