### ISSUE TITLE
Disable logging to console

### ISSUE THREAD

**Issue by unclebobo** [flapdoodle-oss/de.flapdoodle.embed.mongo#72]
I followed the steps recommended here https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/9 , I provided my own IProgressListener and redirected process output to file, but still it logs to console.

**Comment by takanuva15** [comment]
lol I found this issue while trying to turn off logging within a unit test using Spring's `@DataMongoTest` which uses flapdoodle under the hood. I was able to disable logging by specifying the argument `logging.level.org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo=WARN`.

For the unit test, I put it in a Spring annotation:
```java
@TestPropertySource(properties = {
    "spring.mongodb.embedded.version=4.0.9",
    "logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG",
    "logging.level.org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongo=WARN"
})
```

**Comment by F-Node-Karlsruhe** [comment]
sadly could not produce more output

```
logging:
  level:
    de:
      flapdoodle:
        embed=DEBUG:



org:
  springframework:
    .boot:
      autoconfigure:
        mongo:
          embedded:
            EmbeddedMongo=DEBUG:
    data:
      mongodb:
        core:
          MongoTemplate=DEBUG:
```
